# Tell Nixpacks to use Python
providers = ["python"]

[phases.setup]
# Use Python 3.11 and install pip and gunicorn globally via Nix
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.gunicorn"]

[phases.install]
# Install other Python dependencies globally using the Nix-provided pip
# Remove venv creation
cmds = [
    "pip install --no-cache-dir -r backend/requirements.txt"
]

[start]
# Command to run the Flask application using Gunicorn
# Call gunicorn directly, as it should be globally available from Nix setup
cmd = "gunicorn --bind 0.0.0.0:$PORT backend.app:app"
