# Tell Nixpacks to use Python
providers = ["python"]

[phases.setup]
# Use Python 3.11 and install ALL dependencies globally via Nix
nixPkgs = [
    "python311",
    "python311Packages.pip", # Keep pip just in case, but primarily rely on Nix packages below
    "python311Packages.flask",
    "python311Packages.python-dotenv",
    "python311Packages.requests",
    "python311Packages.apify-client",
    "python311Packages.openai",
    "python311Packages.gunicorn"
]

[start]
# Command to run the Flask application using Gunicorn
# Call gunicorn directly, as it should be globally available from Nix setup
cmd = "gunicorn --bind 0.0.0.0:$PORT backend.app:app"
