# Tell Nixpacks to use Python
providers = ["python"]

[phases.setup]
# Use Python 3.11 and install pip via Nix
# Remove gunicorn from here, it will be installed via pip into the venv
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
# Create venv, then use the venv's python/pip to install requirements
cmds = [
    "python -m venv /opt/venv",
    "/opt/venv/bin/python -m pip install --upgrade pip", # Ensure pip is up-to-date within venv
    "/opt/venv/bin/python -m pip install --no-cache-dir -r backend/requirements.txt"
]

[start]
# Command to run the Flask application using Gunicorn
# Use the venv's python to run gunicorn as a module
cmd = "/opt/venv/bin/python -m gunicorn --bind 0.0.0.0:$PORT backend.app:app"
